### ISSUE TITLE
mmode.sh WPS mode problem

### ISSUE THREAD

**Issue by dverlik** [dverlik/bib_students#2]
Scripts `mmode.sh` and `wpsh.sh` do not check if the current `airodump-ng` installed has the `--wps` option, which could lead to script errors.

Скрипты `mmode.sh` и `wpsh.sh` не проверяют, есть ли у текущей установленной версии `airodump-ng` режим `--wps`, что может привести к ошибкам выполнения скрипта.

**Comment by dodgy-mercurius** [comment]
Предлагаю грепать или парсить вывод <code>aircrack-ng --help</code> на предмет версии.

**Comment by MrShadowZ** [comment]
echo "Checking airodum-ng WPS..."
if airodump-ng | grep -q "Display WPS information"
then
	#code
else
	echo "You have old version aircrack-ng or not have this program"
	read -p "Install aircrack-ng? [Y/n]:" DWN
	if [ "$DWN" == "Y" -o "$DWN" == "y" ]
	then
		apt-get autoremove aircrack-ng #Без удаления программа не хочет правильно работать
		apt-get install aircrack-ng
		read -p "Reboot your pc? [Y/n]:" REB
		if [ "$REB" == "Y" -o "$REB" == "y" ]
		then
			reboot #Без перезагрузки программа не хочет правильно работать
		else
			exit 0
		fi
	else
		exit 0
	fi
fi
